apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::478567332414:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-Ls8Q1L1rxLzY
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::160885265516:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::160885265516:user/ramesh
      username: ramesh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::160885265516:user/john
      username: john
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::160885265516:user/rahim
      username: rahim
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-18T04:14:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1227"
  uid: e0695a13-2a6e-41aa-9500-624f035bba89

